name: Android CD

on:
  push:
    tags: [ 'v*.*.*' ]

env:
  key_alias: ${{ secrets.KEY_ALIAS }}
  prev_key_alias: ${{ secrets.PREV_KEY_ALIAS }}
  migrating_version: 4.0.0
jobs:
  build:
    name: Build & Sign AAB
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create a Location Properties File
      run: echo "key_alias=$key_alias\nprev_key_alias=$prev_key_alias\nmigrating_version=$migrating_version" >> local.properties

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup Gradle Cache
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-home-cache-cleanup: true

    - name: Build Release with Gradle
      run: ./gradlew bundleRelease

    - name: Sign AAB
      id: sign
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/bundle/release
        signingKeyBase64: ${{ secrets.KEYSTORE }}
        alias: ${{ secrets.SIGNING_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
        keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}

    - name: Upload app bundle as artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-bundle
        path: app/build/outputs/bundle/release/app-release.aab

    - run: echo Build status report=${{ job.status }}

  deploy:
    name: Deploy AAB to Play Store
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download AAB
        uses: actions/download-artifact@v4
        with:
          name: app-bundle

      - name: Publish to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: '${{ secrets.SERVICE_ACCOUNT_JSON }}'
          packageName: com.benatt.passwordsmanager
          releaseFiles: '${{ github.workspace }}/app-release.aab'
          track: production
